"use strict"

const data = {

	cards: [
		null,
		{ side: "Versailles", ops: 1, name: "Jules Decatel" },
		{ side: "Versailles", ops: 1, name: "The Murder of Vincenzini" },
		{ side: "Versailles", ops: 1, name: "Brassardiers" },
		{ side: "Versailles", ops: 1, name: "Jules Ferry" },
		{ side: "Versailles", ops: 1, name: "Le Figaro" },
		{ side: "Versailles", ops: 1, name: "Général Louis Valentin" },
		{ side: "Versailles", ops: 1, name: "Général Espivent" },
		{ side: "Versailles", ops: 1, name: "Les Amis de l'Ordre" },
		{ side: "Versailles", ops: 2, name: "Socialist Newspaper Ban" },
		{ side: "Versailles", ops: 2, name: "Fortification of Mont-Valérien" },
		{ side: "Versailles", ops: 2, name: "Adolphe Thiers" },
		{ side: "Versailles", ops: 2, name: "Otto von Bismarck" },
		{ side: "Versailles", ops: 2, name: "Général Ernest de Cissey" },
		{ side: "Versailles", ops: 2, name: "Colonel de Lochner" },
		{ side: "Versailles", ops: 2, name: "Jules Favre" },
		{ side: "Versailles", ops: 2, name: "Hostage Decree" },
		{ side: "Versailles", ops: 4, name: "Maréchal Macmahon" },
		{ side: "Commune", ops: 1, name: "Paule Minck" },
		{ side: "Commune", ops: 1, name: "Walery Wroblewski" },
		{ side: "Commune", ops: 1, name: "Banque de France" },
		{ side: "Commune", ops: 1, name: "Le Réveil" },
		{ side: "Commune", ops: 1, name: "Execution of Generals" },
		{ side: "Commune", ops: 1, name: "Les Cantinières" },
		{ side: "Commune", ops: 1, name: "Eugène Protot" },
		{ side: "Commune", ops: 1, name: "Paul Cluseret" },
		{ side: "Commune", ops: 2, name: "Gaston Crémieux" },
		{ side: "Commune", ops: 2, name: "Luise Michel" },
		{ side: "Commune", ops: 2, name: "Jaroslav Dombrowski" },
		{ side: "Commune", ops: 2, name: "Raoul Rigault" },
		{ side: "Commune", ops: 2, name: "Karl Marx" },
		{ side: "Commune", ops: 2, name: "Blanquists" },
		{ side: "Commune", ops: 2, name: "Général Lullier" },
		{ side: "Commune", ops: 2, name: "Jules Vallès" },
		{ side: "Commune", ops: 4, name: "Charles Delescluze" },
		{ side: "Neutral", ops: 3, name: "Conciliation" },
		{ side: "Neutral", ops: 3, name: "Georges Clemenceau" },
		{ side: "Neutral", ops: 3, name: "Archbishop Georges Darboy" },
		{ side: "Neutral", ops: 3, name: "Victor Hugo" },
		{ side: "Neutral", ops: 3, name: "Léon Gambetta" },
		{ side: "Neutral", ops: 3, name: "Elihu Washburne" },
		{ side: "Neutral", ops: 3, name: "Freemason Parade" },
		{ side: "Objective", ops: 0, name: "Paris Cannons", region: "Butte Montmartre" },
		{ side: "Objective", ops: 0, name: "Aux Barricades!", region: "Buttes-Aux-Cailles" },
		{ side: "Objective", ops: 0, name: "Commune's Stronghold", region: "Père Lachaise" },
		{ side: "Objective", ops: 0, name: "Fighting in Issy Village", region: "Fort d'Issy" },
		{ side: "Objective", ops: 0, name: "Battle of Mont-Valérien", region: "Mont-Valérien" },
		{ side: "Objective", ops: 0, name: "Raid on Château de Vincennes", region: "Château de Vincennes" },
		{ side: "Objective", ops: 0, name: "Revolution in the Press", region: "Press" },
		{ side: "Objective", ops: 0, name: "Pius IX", region: "Catholic Church" },
		{ side: "Objective", ops: 0, name: "Socialist International", region: "Social Movements" },
		{ side: "Objective", ops: 0, name: "Royalists Dissension", region: "Royalists" },
		{ side: "Objective", ops: 0, name: "Rise of Republicanism", region: "Republicans" },
		{ side: "Objective", ops: 0, name: "Legitimacy", region: "National Assembly" },
	],

	space_names: [
		"Red Cube Pool 1",
		"Red Cube Pool 2",
		"Red Cube Pool 3",
		"Red Crisis Track Start",
		"Red Crisis Track Escalation",
		"Red Crisis Track Tension",
		"Red Crisis Track Final Crisis",
		"Red Bonus Cubes 1",
		"Red Bonus Cubes 2",
		"Red Bonus Cubes 3",
		"Blue Cube Pool",
		"Blue Crisis Track Start",
		"Blue Crisis Track Escalation",
		"Blue Crisis Track Tension",
		"Blue Crisis Track Final Crisis",
		"Blue Bonus Cubes 1",
		"Blue Bonus Cubes 2",
		"Blue Bonus Cubes 3",
		"Prussian Collaboration 1",
		"Prussian Collaboration 2",
		"Prussian Collaboration 3",
		"Royalists",
		"National Assembly",
		"Republicans",
		"Catholic Church",
		"Press",
		"Social Movements",
		"Mont-Valérien",
		"Butte Montmartre",
		"Fort d'Issy",
		"Butte-Aux-Cailles",
		"Père Lachaise",
		"Château de Vincennes",
		"Prussian Occupied Territory",
		"Versailles HQ",
	],
}

if (typeof module !== 'undefined')
	module.exports = data
